version: '3'

services:
  backend:
    image: eeshuyadav/osdag-web-backend:v1.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  
  frontend:

    image: eeshuyadav/osdag-web-frontend:v1.0
    # build:
    #   context: ./osdagclient
    #   dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    volumes:
      - ./osdagclient:/app
    environment:
      - CHOKIDAR_USEPOLLING=true 
    command: npm run dev 


  db:
    # image: postgres:14
    image: eeshuyadav/postgres:v1.0
    environment:
      # POSTGRES_USER: myuser
      # POSTGRES_PASSWORD: mypassword
      # POSTGRES_DB: mydb

      POSTGRES_USER: osdagdeveloper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_Intg_osdag
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
