version: '3'

services:
  backend:
<<<<<<< HEAD
    # image: eeshuyadav/osdag-web-backend:v1.1
=======
>>>>>>> 3b45bbd3f17894acd9f895a4a3779ea222e8f4cf
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  
  frontend:
<<<<<<< HEAD

    # image: eeshuyadav/osdag-web-frontend:v1.1
=======
>>>>>>> 3b45bbd3f17894acd9f895a4a3779ea222e8f4cf
    build:
      context: ./osdagclient
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    volumes:
      - ./osdagclient:/app
    environment:
      - CHOKIDAR_USEPOLLING=true 
    command: npm run dev 


  db:
    image: postgres:14
<<<<<<< HEAD
    # image: eeshuyadav/postgres:v1.1
=======
>>>>>>> 3b45bbd3f17894acd9f895a4a3779ea222e8f4cf
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
<<<<<<< HEAD
      - "5434:5432"
=======
      - "5432:5432"
>>>>>>> 3b45bbd3f17894acd9f895a4a3779ea222e8f4cf
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
